### PR TITLE
Added snake game.

### PR DESCRIPTION
**Pull request by MayankUghade**
**Added a responsive snake game which will remind you of your childhood games.**
**Hope you like it.**

### CODE REVIEW

**Comment by Priyanshu85** [comment]
Please add this into the website as a Tool!

**Comment by MayankUghade** [comment]
Hey @Priyanshu85 added the game to the website,
please check and merge my file.

**Comment by MayankUghade** [comment]
@Priyanshu85 please merge my PR ,
Or if there is any problem please let me know.

**Comment by Priyanshu85** [comment]
Thanks @MayankUghade

**Pull request merged**
