### PR TITLE
Book Management app added

### PR DESCRIPTION
**Pull request by rohit010pro**

### CODE REVIEW

**Comment by Priyanshu85** [comment]
Not a good Contribution @rohit010pro !!....Kindly resolve or add any issue first!

**Comment by rohit010pro** [comment]
Ok

**Comment by rohit010pro** [comment]
> Not a good Contribution @rohit010pro !!....Kindly resolve or add any issue first!

@Priyanshu85  can i add other small project?

**Comment by Priyanshu85** [comment]
> > Not a good Contribution @rohit010pro !!....Kindly resolve or add any issue first!
> 
> @Priyanshu85 can i add other small project?

See the other issues...like adding a game or a tool or making site responsive...and it should reflect on the main website!!

**Comment by rohit010pro** [comment]
Ok

**Comment by rohit010pro** [comment]
> > > Not a good Contribution @rohit010pro !!....Kindly resolve or add any issue first!
> > 
> > 
> > @Priyanshu85 can i add other small project?
> 
> See the other issues...like adding a game or a tool or making site responsive...and it should reflect on the main website!!

I have added book management app

**Comment by Priyanshu85** [comment]
Nice @rohit010pro !!

**Comment by rohit010pro** [comment]
Thanks!

**Pull request merged**
