### PR TITLE
added india map linking to its folk dances

### PR DESCRIPTION
**Pull request by Swastik200**
hope it may be denoted as one interesting feature

### CODE REVIEW

**Comment by Priyanshu85** [comment]
Did not got what you have done!!

**Comment by Priyanshu85** [comment]
@Swastik200

**Comment by Swastik200** [comment]
Can you plz check index.html
And if any issues I will rectify it soon

**Comment by Swastik200** [comment]
done plz check

**Comment by Swastik200** [comment]
plz check

**Comment by Priyanshu85** [comment]
Okay NP @Swastik200

**Pull request merged**
