### PR TITLE
connect four :)

### PR DESCRIPTION
**Pull request by aditi5050**
A fun Javascript game :)

### CODE REVIEW

**Comment by Priyanshu85** [comment]
THankyou for your intrest in the Repo...Kindlly add this game in the main website.

**Comment by aditi5050** [comment]
Can  you please explain again by what do you mean by saying adding it to
main website

**Comment by aditi5050** [comment]
Yeah, sure will do so

**Comment by aditi5050** [comment]
Hey , I am but am still not getting it as in what is to be done

**Comment by Priyanshu85** [comment]
https://deploy-preview-28--webtools-kitretsu.netlify.app/

This is how the website will be looking after your contribution and I cant see any changes in the website!!!

**Comment by Priyanshu85** [comment]
Kindly add your app in main index.html @aditi5050

**Comment by aditi5050** [comment]
Shall I close this PR and instead of this add another game as I am facing some issues with it .

**Comment by Priyanshu85** [comment]
> Shall I close this PR and instead of this add another game as I am facing some issues with it .

Sure!!! @aditi5050

**Pull request closed without merging**
